### ISSUE TITLE
Temporary tables cannot be created

### ISSUE THREAD

**Issue by cxiiiiiii** [xzkostyan/clickhouse-sqlalchemy#105]
When I use clickhouse-sqlalchemy in hue, the version of clickhouse-sqlalchemy is 0.1.4, I try to create temporary table and return :
"message: Code: 113, e.displayText() = DB::Exception: There is no session, e.what() = DB::Exception"

There should be no session_id passed in.
How do I pass the session_id?

**Comment by xzkostyan** [comment]
Can you provide minimal piece of python code that reproduces the problem?
