### ISSUE TITLE
Is it possible to make a join across tables from different schemas(databases)?

### ISSUE THREAD

**Issue by justtoreply** [xzkostyan/clickhouse-sqlalchemy#106]
I'm new at your dialect (and orm as well)
let's say there are two tables from two databases
`first_db_uri =  'clickhouse://default:@localhost/test_1'`
`second_db_uri =  'clickhouse://default:@localhost/test_2'`

as it's said two separated engines need to be created:
`first_engine = create_engine(first_db_uri)`
`second_engine = create_engine(second_db_uri)`

and sessions:
`first_sessions = make_session(first_engine)`
`second_sessions = make_session(second_engine)`

lest's suppose we got two qqs
`q_1 = first_session.query()`
`q_2 = second_sessions.query()`

How can I make a join between'em if they are corresponded to different sessions->engines so on?

thank you ahead

**Comment by xzkostyan** [comment]
Hi.

It's always possible to make join with `remote`/`remoteSecure` function: https://clickhouse.tech/docs/en/sql-reference/table-functions/remote/

Join between different sessions/engines are not supported.

Also, you can try `__table_args__` in model/table declaration for specifying different database. But, I'm not sure that it will work:

```python
class Model(base):
    # columns

    __table_args__ = ({'schema': 'another_database'},)
```

**Comment by justtoreply** [comment]
Thanks for suggestion!
I've tried remote in Tabix and it works.
But I have no idea how to use this function inside sqlalchemy and your dialect.
Could you gile a lil example of using remote connection by this stack?
Thanks!

**Comment by xzkostyan** [comment]
Sorry for late response. If you have two databases on the same ClickHouse server you can try `__table_args__` hack.

Table A in db test.
Table B in db test2.

```python
from sqlalchemy import create_engine, Column, MetaData

from clickhouse_sqlalchemy import Table, make_session, get_declarative_base, types, engines

uri = 'clickhouse+native://localhost/test'

engine = create_engine(uri)
session = make_session(engine)
metadata = MetaData(bind=engine)

Base = get_declarative_base(metadata=metadata)

class A(Base):
    id = Column(types.Date, primary_key=True)
    value = Column(types.Int32)

    __table_args__ = (
        engines.Memory(),
    )


class B(Base):
    id = Column(types.Date, primary_key=True)
    value = Column(types.Int32)

    __table_args__ = (engines.Memory(), {'schema': 'test2'})

metadata.create_all()

print(session.query(A.id, B.value).join(B, A.id == B.id))
```

Of course the way without `remote` is preferred for join within one ClickHouse server.
Will output:

```sql
SELECT "A".id AS "A_id", test2."B".value AS "test2_B_value" 
FROM "A" INNER JOIN test2."B" ON "A".id = test2."B".id
```

Trick with `remote` function (assuming that all tables have been created with pass snipped):

```python
from sqlalchemy import create_engine, Column, MetaData, func

from clickhouse_sqlalchemy import Table, make_session, get_declarative_base, types, engines

uri = 'clickhouse+native://localhost/test'

engine = create_engine(uri)
session = make_session(engine)
metadata = MetaData(bind=engine)

Base = get_declarative_base(metadata=metadata)

class A(Base):
    id = Column(types.Date, primary_key=True)
    value = Column(types.Int32)

    __table_args__ = (
        engines.Memory(),
    )

# "Manual" columns definition for table B.
id_col = Column('id', types.Date)
value_col = Column('id', types.Int32)

sq = session.query(id_col.label('id'), value_col.label('value')) \
    .select_from(func.remote('localhost', 'test2', 'B', 'default', '')) \
    .subquery()

print(session.query(A.id, sq.c.value).join(sq, sq.c.id == A.id))
```

Will render into following SQL:

```sql
SELECT "A".id AS "A_id", anon_1.value AS anon_1_value 
FROM "A" INNER JOIN (SELECT id AS id, id AS value 
FROM remote(%(remote_1)s, %(remote_2)s, %(remote_3)s, %(remote_4)s, %(remote_5)s)) AS anon_1 ON anon_1.id = "A".id
````
