### ISSUE TITLE
limit_by support

### ISSUE THREAD

**Issue by bbcVld** [xzkostyan/clickhouse-sqlalchemy#109]
Does clickhouse-sqlalchemy support limit_by method, which generates query like this:
``` 
SELECT time, name, value FROM table LIMIT 2 BY name
```
?

Or how it can be emulated?

**Comment by bbcVld** [comment]
I looked at tests and find that there is a support in master but not in last release.
So, my question is when you are planning to release new version.

And LIMIT BY is legal without GROUP BY part. I hope it works.

**Comment by xzkostyan** [comment]
`LIMIT BY` is supported: https://clickhouse-sqlalchemy.readthedocs.io/en/latest/features.html#limit-by
