### ISSUE TITLE
failed to query in SQL Editor in apache superset

### ISSUE THREAD

**Issue by rogerlzp** [xzkostyan/clickhouse-sqlalchemy#110]
**Describe the bug**
1. connect to clickhouse successfully
2. try a query: "select * from  aaa"  in Apache Superset  SQL Editor，
it will return with the error "
 Unexpected Error
clickhouse error: 'NoneType' object has no attribute 'startswith'
"

**To Reproduce**
run any sql in Apache Superset

**Expected behavior**
Should return the result

**Versions**
Apache Superset 0.38.0
clickhouse-driver:        0.1.5
clickhouse-sqlalchemy:    0.1.4
Python 3.6.10

**Comment by xzkostyan** [comment]
Are you trying to use this library or `sqlalchemy-clickhouse` in superset? The second is recommended according to [docs](https://superset.apache.org/docs/databases/clickhouse/).
