### ISSUE TITLE
"Nullable" type not working with undefined values.

### ISSUE THREAD

**Issue by diogobaeder** [xzkostyan/clickhouse-sqlalchemy#137]
**Describe the bug**
When having a Nullable column and not setting the related property in an entity instance, trying to add the object to the session and then committing raises the following error:
```
  File "clickhouse_driver/bufferedwriter.pyx", line 54, in clickhouse_driver.bufferedwriter.BufferedWriter.write_strings
AttributeError: 'NoneType' object has no attribute 'encode'
```
which seems to be the driver attempting to save the undefined property as a string (when it's not - it's `None` since it wasn't defined).

**To Reproduce**
```python
class SomeModel(Base):
    something = Column(types.Nullable(types.String))

instance = SomeModel()
session.add(instance)
session.commit()  # here's where the exception happens
```

**Expected behavior**
The object should be added to the table with the non-empty columns filled in, instead of raising an error.

**Versions**

- Version of package with the problem: 0.1.6
- Python version: 3.9.6

**Comment by diogobaeder** [comment]
I can see that String columns have a `write_items` method in `clickhouse-driver`, but I don't see the same method implemented in the `NullColumn` class; Perhaps it's somewhat related to that? I don't know, I'm just wondering if the issue is perhaps in the driver itself and not `clickhouse-sqlalchemy`...

**Comment by diogobaeder** [comment]
Sorry for the flood, but one more important detail: when inserting the data by using `session.execute(table.insert(), data)`, it works just fine. This is not ideal though - I want to be able to properly add the objects to the session and flush it without the error.

**Comment by danielgafni** [comment]
Seems like I just posted a very similar issue #189

**Comment by diogobaeder** [comment]
Closing as a duplicate of #189
