### ISSUE TITLE
Clickhouse does not accept a password without specifying a driver

### ISSUE THREAD

**Issue by orcvoin** [xzkostyan/clickhouse-sqlalchemy#138]
**Describe the bug**
It is required to explicitly specify the driver to configure the connection with a password, even if the default http is used

**To Reproduce**
from sqlalchemy import create_engine
`from sqlalchemy import create_engine
engine = create_engine('clickhouse://default:password@host.com:8123/database', echo=False)`
The password is ignored for this connection setup. When executing a connect request, clickhouse reports the "Exception: Code: 194, e.displayText() = DB::Exception: Password required for user default (version 20.1.6.30 (official build))" error

If you explicitly specify the driver in the connection settings, the password is accepted correctly
`engine = create_engine('clickhouse+http://default:password@host.com:8123/database', echo=False)`
Perhaps the solution would be to explicitly indicate in the documentation the need to register the http driver if the connection is with a password

**Expected behavior**
Behavior without specifying an explicit "clickhouse + http" driver is similar to "clickhouse" +default(http)
If the default user is not password protected, connecting without specifying "http" works correctly
**Versions**
- Version of package with the problem.
- 0.1.6 
- Python version.
- 3.8

**Comment by xzkostyan** [comment]
I'm unable to reproduce this problem with python 3.8.12 and clickhouse-sqlalchemy 0.1.6.
