### ISSUE TITLE
Partition by EXPRESSION

### ISSUE THREAD

**Issue by bralbral** [xzkostyan/clickhouse-sqlalchemy#142]
Hello!

How can i pass` PARTITION BY toYYYYMM(date)` in expression below?

```

   __table_args__ = (
            engines.MergeTree(
                primary_key=[user], order_by=[user, date_time], partition_by=[user]
            ),
            {"extend_existing": True},
        )
```

**Comment by xzkostyan** [comment]
Hi.

You can use SA `func`. See examples in tests: https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/master/tests/engines/test_compilation.py#L70 This should also work for `PARTITION BY`.

**Comment by bralbral** [comment]
> Hi.
> 
> You can use SA `func`. See examples in tests: https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/master/tests/engines/test_compilation.py#L70 This should also work for `PARTITION BY`.

Yes, it fits. Thank you for quick response!
