### ISSUE TITLE
Can't create comment of a table field with class map

### ISSUE THREAD

**Issue by flyly0755** [xzkostyan/clickhouse-sqlalchemy#149]
**Describe the bug**
with sql command to creat a table, we can use COMMENT attribute to set a comment for a field.
CREATE TABLE stdfdb.NewTable2
(
    `Column4` String COMMENT 'TEST',

    `Column5` String
)
ENGINE = MergeTree()
ORDER BY Column1
SETTINGS index_granularity = 8192

but with clickhouse-sqlalchemy classs map:
class TbFile(Base, CommonDB2):
    __tablename__ = 'tb_file'
    __table_args__ = {'comment': 'File Info Table V1.0'}
    # id = Column(types.UUID, primary_key=True)
    filename = Column(types.String, primary_key=True)
    type = Column(types.String, **comment='test it'**)
    __table_args__ = (
        engines.MergeTree(partition_by='filename', order_by='filename', primary_key='filename'),
    )
The comment function not works. after create table with ORM, we can't see the comment 'test it' with the field _type_
**To Reproduce**
See above

**Expected behavior**
Can see the comment 'test it' with the field _type_

**Versions**

- clickhouse-sqlalchemy0.1.6
- Python3.8.5

**Comment by xzkostyan** [comment]
Table and columns comments support was added to latest master.
