### ISSUE TITLE
not support MaterializedMySQL

### ISSUE THREAD

**Issue by phpsxg** [xzkostyan/clickhouse-sqlalchemy#158]
**Describe the bug**
When using clickhouse-sqlalchemy to query data, the error is as follows:
`  File "/home/sxg/miniconda3/lib/python3.9/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 868, in _reflect_engine
    engine = engine_cls.reflect(table, **e)
AttributeError: 'NoneType' object has no attribute 'reflect'`

Locate the problem and found that the _reflect_engine method in the clickhouse_sqlalchemy/drivers/base.py file, the obtained table_name is MaterializedMySQL, resulting in the obtained engine being empty

Found that the clickhouse_sqlalchemy/engines/__init__.py file does not have MaterializedMySQL

How to solve this problem, thank you

**Versions**

- python 3.9.5
- clickhouse-sqlalchemy         0.1.7

**Comment by xzkostyan** [comment]
Try installing from latest master from github. This [was fixed](a96e616afc4692878926a0ef8032ab29fc171143) a couple of weeks ago.

**Comment by phpsxg** [comment]
Thanks~

> Try installing from latest master from github. This [was fixed](a96e616afc4692878926a0ef8032ab29fc171143) a couple of weeks ago.
> 
> Another solution: #151

Thanks
