### ISSUE TITLE
how to add part of all tables in one shard

### ISSUE THREAD

**Issue by flyly0755** [xzkostyan/clickhouse-sqlalchemy#160]
for example, with tableA and tableB, I want add tableA and tableB in shard1, and add tableA only in shard2,
it's easy to add all 2 tables in shard1 with command Base.metadata.create_all(bind=bind),
but how can i just add tableA in shard2?
i have a try with command
Base.metadata.create_all(bind=bind, tables=tableA)
but failed with error:
clickhouse_sqlalchemy.exceptions.DatabaseException: Orig exception: Code: 60, e.displayText() = DB::Exception: Table stdfdb.tableB doesn't exist. (version 20.8.11.17 (official build))
talbeA and tableB both with Base attribute, whether first time with Base.metadata.create_all will always try to add both tables?
Then delete tableA, so you can use Base.metadata.create_all(bind=bind, tables=tableA) to just add tableA?

**Comment by xzkostyan** [comment]
How would you do the same with `clickhouse-client`?

**Comment by xzkostyan** [comment]
Not enough information. Feel free to reopen with additional info.
