### ISSUE TITLE
clickhouse-sqlalchemy==0.1.7 does not support SQLAlchemy==1.4

### ISSUE THREAD

**Issue by phpsxg** [xzkostyan/clickhouse-sqlalchemy#161]
**Describe the bug**
I want to use sqlalchemy to connect to clickhouse asynchronously. SQLAlchemy==1.4 supports asynchrony, but I find that clickhouse-sqlalchemy==0.1.7 is incompatible with SQLAlchemy==1.4. What should I do if I want to use sqlalchemy to connect to clickhouse asynchronously? thanks

`Traceback (most recent call last):
  File "/home/sxg/miniconda3/lib/python3.9/site-packages/clickhouse_sqlalchemy/ext/clauses.py", line 3, in <module>
    from sqlalchemy.sql.elements import (
ImportError: cannot import name '_literal_as_label_reference' from 'sqlalchemy.sql.elements' (/home/sxg/miniconda3/lib/python3.9/site-packages/sqlalchemy/sql/elements.py)`
**Versions**

- clickhouse-sqlalchemy==0.1.7
- SQLAlchemy==1.4

**Comment by xzkostyan** [comment]
`clickhouse-sqlalchemy==0.1.7` [is not compatible](https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/0.1.7/setup.py#L102) with SA 1.4.
See [this issue](https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/129) for 1.4 support. You can try asynchronous usage. Waiting for your feedback in #129.

**Comment by xzkostyan** [comment]
Version 0.2.0 with SQLAlchemy 1.4 support is released.
