### ISSUE TITLE
How does sqlalchemy connect to the cluster

### ISSUE THREAD

**Issue by phpsxg** [xzkostyan/clickhouse-sqlalchemy#162]
The code for sqlalchemy to connect to a single machine is as follows：
conn_str = 'clickhouse://default:@localhost/default' engine = create_engine(conn_str)

How does sqlalchemy connect to the cluster?Thanks~

**Comment by xzkostyan** [comment]
`clickhouse-sqlalchemy` as `clickhouse-client ` always connects only to particular node of cluster. Therefore SELECTs and INSERTs executes on single node. However some DDL queries can be executed with `ON CLUSTER x` clause and DDL will be executed on every cluster node. This is ClickHouse server functionality.

**Comment by phpsxg** [comment]
> 

Does it mean that clickhouse-sqlalchemy query does not support clustering, because it wants to improve the query speed, the cluster is created. Is there any other solution?Thanks~

**Comment by xzkostyan** [comment]
This dialect doesn't split queries into parts for different replicas for further merging after completion. I don't know tools with such solutions. It seems that you are looking for [Distributed Table Engine](https://clickhouse.com/docs/en/engines/table-engines/special/distributed/).
