### ISSUE TITLE
 SAWarning: Dialect clickhouse:http will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.

### ISSUE THREAD

**Issue by Speccy-Rom** [xzkostyan/clickhouse-sqlalchemy#169]
How to get around this without losing performance?

**Comment by xzkostyan** [comment]
Is there the same issue with `clickhouse+native`dialect? How can we reproduce the problem?

**Comment by Speccy-Rom** [comment]
Hi! any news on this issue?

**Comment by Speccy-Rom** [comment]
Hi! any news on this issue?

**Comment by xzkostyan** [comment]
I suppose we can just add `supports_statement_cache = True` to drivers. Fix merged into master.

**Comment by xzkostyan** [comment]
Version 0.2.1 with fix is released.
