### ISSUE TITLE
sqlalchemy version >= 1.4.x breaking 

### ISSUE THREAD

**Issue by RobinDuhan** [xzkostyan/clickhouse-sqlalchemy#170]
Good evening folks, 

In setup.py we have a commit that is 17 days old which changed the sqlalchemy requirement to be from 1.4-1.5 from 1.3-1.4. But sqlalchemy version 1.4 and above have some changes that are breaking in one form or the other. 

One example - https://stackoverflow.com/questions/66644975/importerror-cannot-import-name-columnentity-from-sqlalchemy-orm-query

Suggesting to make changes in install_requires to have sqlalchemy from 1.3-1.5 for now while we can fix the breaking changes in some packages. 

Thanks.

**Comment by xzkostyan** [comment]
This package depends on particular SQLAlchemy version. One version can't handle both 1.3.x and 1.4.x. You can install versions less than 0.2.0 for 1.3 compatibility.
