### ISSUE TITLE
Compilation bug when using strings instead of sqlalchemy Columns in engine args

### ISSUE THREAD

**Issue by robinovitch61** [xzkostyan/clickhouse-sqlalchemy#173]
**Describe the bug**
Unexpected error when compiling create statement when using a string reference to a column in an order_by engine arg instead of the sqlalchemy Column.

**To Reproduce**
I've written a repro test case for it [here](https://github.com/robinovitch61/clickhouse-sqlalchemy/commit/019a641a99cef8e63ec189f55fdd785550d5db1f)

Invoked pytest in the environment listed below with
```
pytest tests/engines -k test_order_by_text
```

Text will pass if this is changed `order_by=(text('toYYYYMM(date)'), 'x')` -> `order_by=(text('toYYYYMM(date)'), x)`.

I see other places where columns in order by are referred to by their string values, so I assume this isn't unexpected usage ([example](https://github.com/robinovitch61/clickhouse-sqlalchemy/commit/019a641a99cef8e63ec189f55fdd785550d5db1f#diff-ae6c07ead022e91ce47681d0bbb750cb4857318b4bc7152276c93fd03875a31aR540))

**Expected behavior**
Compilation should work as expected when referring to column by string, e.g. `order_by=(text('toYYYYMM(date)'), 'x')`

**Versions**

```
❯ python --version
Python 3.8.11

❯ pip freeze
attrs==21.4.0
backports.zoneinfo==0.2.1
certifi==2021.10.8
charset-normalizer==2.0.12
clickhouse-driver==0.2.3
clickhouse-sqlalchemy @ file:///Users/leo/projects/clickhouse-sqlalchemy
greenlet==1.1.2
idna==3.3
iniconfig==1.1.1
packaging==21.3
parameterized==0.8.1
pluggy==1.0.0
py==1.11.0
pyparsing==3.0.7
pytest==7.1.1
pytz==2022.1
pytz-deprecation-shim==0.1.0.post0
requests==2.27.1
responses==0.20.0
SQLAlchemy==1.4.32
tomli==2.0.1
tzdata==2022.1
tzlocal==4.1
urllib3==1.26.9
```

**Comment by xzkostyan** [comment]
You can reference columns by name or directly by variable if it's possible. See [contraints](https://docs.sqlalchemy.org/en/14/core/constraints.html) docs.

Under the hood string to real column mapping is done here: https://github.com/zzzeek/sqlalchemy/blob/rel_1_4_36/lib/sqlalchemy/sql/coercions.py#L222

**Comment by xzkostyan** [comment]
I've dig into this non-trivial issue. Thanks for pointing it out.

**Comment by robinovitch61** [comment]
Thanks @xzkostyan !

**Comment by xzkostyan** [comment]
Version 0.2.1 with fix is released.
