### ISSUE TITLE
Raise error "Please check the system service:Can't load plugin: sqlalchemy.dialects:clickhouse."

### ISSUE THREAD

**Issue by flyly0755** [xzkostyan/clickhouse-sqlalchemy#178]
**Describe the bug**
with clickhouse-sqlalchemy this package, after our project code is packaged, occurs this issue;
but it's normal when i debug with source code which isn't packaged.
search some results on the internet:
https://stackoverflow.com/questions/62688256/sqlalchemy-exc-nosuchmoduleerror-cant-load-plugin-sqlalchemy-dialectspostgre
maybe in some situation, url show write as below?
uri = f"clickhouse+**clickhouse-sqlalchemy**://{user}:{password}@{host}:{port}/{database}"

https://stackoverflow.com/questions/53284762/nosuchmoduleerror-cant-load-plugin-sqlalchemy-dialectssnowflake
or in some situation, should register first?
from sqlalchemy.dialects import registry
registry.register("clickhouse", "base", "dialect")

need for your help:)

**To Reproduce**
from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool
from sqlalchemy.orm import sessionmaker

uri = f"clickhouse://{user}:{password}@{host}:{port}/{database}"
engine = create_engine(uri, echo=False, poolclass=NullPool)
DBsession = sessionmaker(bind=engine)
session = DBsession()

**Expected behavior**
can be connect clichouse successfully without raising error

**Versions**
clickhouse-sqlalchemy==0.2.0

**Comment by xzkostyan** [comment]
Dialects registration takes place in setup.py: https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/master/setup.py#L94. It seems something wrong with your installation.

Try to fresh venv/reinstall the package.

**Comment by xzkostyan** [comment]
Duplicates #179.
