### ISSUE TITLE
"http" driver execute sql error

### ISSUE THREAD

**Issue by Yuanmu93** [xzkostyan/clickhouse-sqlalchemy#18]
## When I use "http" driver to execute sql by sqlalchemy, the returned data not complete, like this:
![image](https://user-images.githubusercontent.com/20705403/41699986-0e47fbdc-7559-11e8-8b73-aa74f86d7dd0.png)

## Besides, when i use pandas.read_sql() method to get data, it cannot get columns, the columns is data, not columns, like this:
![image](https://user-images.githubusercontent.com/20705403/41700331-6d294a92-755a-11e8-805f-4fed16d637c2.png)

**Comment by xzkostyan** [comment]
Hi!

There is the same issue: https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/14

This moment should be properly documented.

**Comment by Yuanmu93** [comment]
Get it, Thank you for help!
