### ISSUE TITLE
how to support clickhouse dialect in sqlalchemy with clickhouse-sqlalchemy

### ISSUE THREAD

**Issue by flyly0755** [xzkostyan/clickhouse-sqlalchemy#181]
with this link https://docs.sqlalchemy.org/en/14/dialects/
don't find clickhouse dialect
usually use extra dialect showed as below:
from sqlalchemy.dialects import registry
registry.register('snowflake', 'snowflake.sqlalchemy', 'dialect')
https://snowflakecommunity.force.com/s/question/0D50Z00009Huss0SAB/how-to-get-pyinstaller-to-pack-snowflake-sqlalchemy-dialect

but how to use with clickhouse-sqlalchemy?
from sqlalchemy.dialects import registry
registry.register('snowflake', 'clickhouse_sqlalchemy', 'dialect')
write like this? notice the underscore

**Comment by xzkostyan** [comment]
This package automatically register dialect in current env. I don't know how to intergrate it with pyinstaller.

Duplicates #179.
