### ISSUE TITLE
It was wrong to create the ClickHouse engine

### ISSUE THREAD

**Issue by wuhuanyan** [xzkostyan/clickhouse-sqlalchemy#20]
### Thank you for your reply.

This is my code:

```
import sqlalchemy as sqla
import pymssql
import pandas as pd

SQL_DB_CONN_STR = 'mssql+pymssql://sa:1@192.168.1.107:1433/UFDATA_008_2015'
CH_DB_CONN_STR = 'clickhouse://default:@192.168. 1.188/zy'


table_name = 'AA_PinYin'
sql = 'select * from dbo.{}'.format(table_name)
sql_engine = sqla.create_engine(SQL_DB_CONN_STR)
ch_engine = sqla.create_engine(CH_DB_CONN_STR)
sql_df = pd.read_sql(sql, sql_engine, chunksize=5000)
num = 1
for i in sql_df:
    if num == 1:
        i.to_sql(name=table_name, con=ch_engine, if_exists='replace')
    else:
        i.to_sql(name=table_name, con=ch_engine, if_exists='append')
    num= num + 1

---------------------------------------------------------------------------
CompileError                              Traceback (most recent call last)
<ipython-input-7-efbf2225776b> in <module>()
     18     print(j)
     19     if num == 1:
---> 20         i.to_sql(name=table_name, con=ch_engine, if_exists='replace')
     21     else:
     22         i.to_sql(name=table_name, con=ch_engine, if_exists='append')
.......
c:\users\jeff\appdata\local\programs\python\python35\lib\site-packages\sqlalchemy\sql\compiler.py in visit_create_table(self, create)
   2481             text += separator + "\t" + const
   2482 
-> 2483         text += "\n)%s\n\n" % self.post_create_table(table)
   2484         return text
   2485 

c:\users\jeff\appdata\local\programs\python\python35\lib\site-packages\clickhouse_sqlalchemy\drivers\base.py in post_create_table(self, table)
    287 
    288         if not engine:
--> 289             raise exc.CompileError("No engine for table '%s'" % table.name)
    290 
    291         return ' ENGINE = ' + self.process(engine)

CompileError: No engine for table 'AA_PinYin'`
```

**Comment by xzkostyan** [comment]
Hi.

This error means that engine for table creation is missed somewhere in pandas dataframe internals.

There is an example of table creation in readme: https://github.com/xzkostyan/clickhouse-sqlalchemy#basic-ddl-support. You should define table at first and afterwards create it.

In your case engine detection can be missed during table reflection from database. Can you test it in pure clickhouse-sqlalchemy?

**Comment by wuhuanyan** [comment]
HI.
Can you set default engine in "clickhouse_sqlalchemy\drivers\base.py in post_create_table(self, table)"?

**Comment by wuhuanyan** [comment]
For example：
```
if not engine:
    # raise exc.CompileError("No engine for table '%s'" % table.name)
    return ' ENGINE = Log '  # + self.process(engine)
return ' ENGINE = ' + self.process(engine)
```
I'm a novice to Python，I don't know what self.process (engine) has done.
But after that, it looks as if it can run normally.

**Comment by aCLr** [comment]
I think it is not right because ENGINE clause is mandatory for CREATE TABLE statement in ClickHouse. 
Your request is the same as if you request the same feature for ClickHouse DBMS.

**Comment by danielgafni** [comment]
Seems like this is still a problem. A default table engine is still not specified.

**Comment by SomeAkk** [comment]
Can we reopen that issue?

**Comment by vietvudanh** [comment]
Why this was closed though? It's a valid error.

**Comment by anishpdoshi** [comment]
Any update on this? In clickhouse, if i've created my table like this:

CREATE TABLE events_processed (
 ...
) ENGINE = ReplacingMergeTree()

do i need to specify `ReplacingMergeTree` somewhere?

**Comment by Lawiss** [comment]
Same error on polars==1.21.0 (which relies on pandas for db writing it seems).
