### ISSUE TITLE
async driver support?

### ISSUE THREAD

**Issue by randomowo** [xzkostyan/clickhouse-sqlalchemy#206]
@xzkostyan will async driver support be added?

sqlalchemy 1.4 already have async support

I have implemented this feature via asynch lib [here](https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/5e67aafcf022f968760c21a1a1f31fd9dfc50308) but it has some issues due to out of sync clickhouse-driver and asynch (asynch has old implementation of some clickhouse-driver features)

I can "patch" asynch and then (after asynch maintainer will approve my pull request) add normal async driver support to clickhouse-sqlalchemy if you don not mind

**Comment by xzkostyan** [comment]
Hi.

Currently I'm not interested in async support. But PRs are always welcome.
