### ISSUE TITLE
Support Boolean ClickHouse type

### ISSUE THREAD

**Issue by AntonFriberg** [xzkostyan/clickhouse-sqlalchemy#212]
**Describe the bug**
Support the ClickHouse `Bool` type.

The boolean data type was added to ClickHouse in `v21.12`

https://clickhouse.com/docs/en/whats-new/changelog/2021#clickhouse-release-v2112-2021-12-15

**Expected behavior**
Be able to use a boolean from the `clickhouse_sqlalchemy.types` module.

**Versions**

- Version of package with the problem.
- <=0.2.2

I wonder if it would be as simple as adding a Boolean type to the `clickhouse_sqlalchemy.types.common` types module referencing the Boolean type from `sqlalchemy.sql.types` similar to how the other types are implemented? Is PR welcome for this feature?

**Comment by xzkostyan** [comment]
Hi.

Yes, PR for this feature is welcome.
