### ISSUE TITLE
how to set partition_by with field value prefix when using engines.MergeTree

### ISSUE THREAD

**Issue by flyly0755** [xzkostyan/clickhouse-sqlalchemy#222]
for example, with TEST_ID field value as partition key, config as below:
```python
engines.MergeTree(partition_by='TEST_ID',
                          order_by='fileid',
                          primary_key='fileid')
```
but if i want to just use TEST_ID field value prefix as partition key, for example, TEST_ID field values ABC_123, DEF_456, just use the first 3 chars(ABC, DEF) as  partition key,
how to implement with code?

**Comment by xzkostyan** [comment]
Hi.

How would you do it in plain SQL?

**Comment by flyly0755** [comment]
> Hi.
> 
> How would you do it in plain SQL?

with plain SQL, with substring function can do it:
PARTITION BY substring(TEST_ID, 1, 4)

**Comment by xzkostyan** [comment]
```
from sqlalchemy import func, text

partition_by=func.substr(text('TEST_ID'), 1, 4),
```

**Comment by flyly0755** [comment]
thanks, it can be set successfully with extra text() method
