### ISSUE TITLE
Is there a way to pass timezone to DateTime?

### ISSUE THREAD

**Issue by utapyngo** [xzkostyan/clickhouse-sqlalchemy#230]
Clickhouse [allows](https://clickhouse.com/docs/ru/sql-reference/data-types/datetime/) passing timezone to DateTime columns:

    `timestamp` DateTime('Europe/Moscow'),

Is there a way to achieve this with clickhouse-sqlalchemy?

**Comment by xzkostyan** [comment]
Yes you can do it with latest master.

**Comment by utapyngo** [comment]
When will you issue a new release?

**Comment by xzkostyan** [comment]
I want accumulate some fixes for 1.4 in new release. I think in a couple of weeks.
