### ISSUE TITLE
INSERT FROM SELECT statement

### ISSUE THREAD

**Issue by Joozty** [xzkostyan/clickhouse-sqlalchemy#24]
Hi, I am trying to insert values from select statement to table. Let's say I have one table `Table1` with columns `A` and `B`. I want select all records from `Table1`, add new column `C` with some value and insert this to second table `Table2`.

But I don't know how to add new column `C`.

My raw SQL query would look like
```sql
INSERT INTO Table2
FROM
     SELECT A, B, `some_value` AS C
     FROM Table1
```

My python code:

```python
from sqlalchemy import cast

# Labels must be present.
select_query =   session.query(Table1).filter(Table.A.in_(ids)).subquery() # How to add new column C?

session.execute(
    Table2.insert()
    .from_select(['A', 'B', 'C'], select_query)
)
```

Thanks in advance.

**Comment by xzkostyan** [comment]
```python
select_query =  session.query(Table1.c.A, Table1.c.B, literal('some_value').label('C'))...
````
