### ISSUE TITLE
Support for Sqlalchemy 2.0?

### ISSUE THREAD

**Issue by mtieuso** [xzkostyan/clickhouse-sqlalchemy#242]
@xzkostyan is there any plan for supporting Sqlalchemy 2.x (released in Jan 2023)

I just updated my sqlalchemy from 1.4 to 2.0.3 and faced this error

```
ImportError: cannot import name '_bind_or_error' from 'sqlalchemy.sql.base' 
```

**Comment by xzkostyan** [comment]
It will be supported eventually.

Now package does not officially support SA > 1.4 https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/master/setup.py#L97

**Comment by chtlp** [comment]
Hi @xzkostyan, we want to use a newer version of Sqlalchemy with clickhouse too. Is there any timeline for supporting the new SA version :)

**Comment by 9en9i** [comment]
Hi @xzkostyan, is there any update on sqlalchemy 2 support?

**Comment by xzkostyan** [comment]
Version 0.3.0 with SA 2.0 support released.
