### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by Noidor1** [xzkostyan/clickhouse-sqlalchemy#247]
Hi! I'm starting to use your project. It looks awesome. 
I noticed that the main branch has long had support for the asynch driver, but there was still no release. 
When to expect it?  It would help me a lot. Thanks!

**Comment by vanchaxy** [comment]
+1, we currently use installed from the last master version, but we need to install git during the build for this. The master release will be very helpful for us.

**Comment by xzkostyan** [comment]
Hi.

It's really good to see you are using latest master and it's just work for you.

I'll make new release at this weekend.

**Comment by xzkostyan** [comment]
Version 0.2.4 is released.
