### ISSUE TITLE
Database addition error with superset

### ISSUE THREAD

**Issue by hemantjadon** [xzkostyan/clickhouse-sqlalchemy#26]
Unable to add new database, it shows the error 

<img width="1188" alt="screen shot 2018-08-16 at 12 28 30 pm" src="https://user-images.githubusercontent.com/11755543/44193272-eddd6d00-a14f-11e8-8662-8eb86abc74f9.png">

There is no exception thrown on the server, As well as no other error response.

**Comment by xzkostyan** [comment]
Hi!

How can I exactly reproduce the problem?

**Comment by hemantjadon** [comment]
You can reproduce this by simply trying to add a clickhouse database to superset. There is no error on stack trace.

**Comment by xzkostyan** [comment]
Can you provide small piece of code that reproduce the problem, please?

**Comment by hemantjadon** [comment]
What I did was:
* Run superset, (in dev mode)
* Try to connect to clickhouse `clichouse://default:@<host>:<port>`
* The error appears.

What I have found out is that, on [L463](https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/master/clickhouse_sqlalchemy/drivers/base.py#L463), it should be `self._execute()` instead of `connection.execute()`, I tried and the db got successfully added.

**Comment by xzkostyan** [comment]
I suppose we can close issue. Follow official superset guide for ClickHouse: https://superset.apache.org/docs/databases/clickhouse/
