### ISSUE TITLE
Clickhouse Asynchronous I/O

### ISSUE THREAD

**Issue by ArijitSinghEDA** [xzkostyan/clickhouse-sqlalchemy#278]
I have a sql query: `SELECT * FROM TABLE1`
The table is stored in a Clickhouse database.

I am running the following code:

```
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

engine = create_async_engine("clickhouse+asynch://host/db")

async with engine.connect() as conn:
    res = await conn.stream(text(query))
    data = await res.partitions(10000)
```

This results into the following error:

```
asynch.errors.ServerException: Code: 12.
DB::Exception: Setting 'max_block_size' cannot be zero
```

What am I doing wrong? My objective is to get data in parallel

**Comment by Simon-Chenzw** [comment]
Asynch may already support this feature in version 0.2.4.
But clickhouse-sqlalchemy still needs some changes.
see long2ice/asynch#24
