### ISSUE TITLE
Add support for Date32

### ISSUE THREAD

**Issue by BTheunissen** [xzkostyan/clickhouse-sqlalchemy#302]
https://github.com/ClickHouse/ClickHouse/issues/9277

Clickhouse `Date` type doesn't support dates before epoch (1970-01-01), due to the underlying representation of the data being an unsigned integer, as such dates before this period cannot be represented by negative values.

This has since been addressed with the `Date32` type using an unsigned 32-bit integer under the hood, and `DateTime64` using an unsigned 64-integer.

I am going to take a look at implementing these types myself with a PR, but would be helpful to know if there is a strong reason why this hasn't already been done and if there are any obvious edge-cases to look for.

**Comment by BTheunissen** [comment]
`DateTime64` is already implemented, edited issue to reflect, but still interested in adding `Date32` support.

**Comment by xzkostyan** [comment]
Hi.

Feel free to make PR. There no strong reason against this feature.
