### ISSUE TITLE
Handling Clickhouse Alembic Migrations for Clickhouse cluster

### ISSUE THREAD

**Issue by vikrant-mah-dhimate** [xzkostyan/clickhouse-sqlalchemy#304]
**Describe the bug**
When you run migration alembic creates table alembic_version only on connected node with clickhouse in cluster mode. (e.g 2 nodes with 2 replicas)

**To Reproduce**
Install clickhouse cluster (e.g. https://github.com/tetafro/clickhouse-cluster) and access it using service endpoint. This randomly connects to any one of the shared-replica from cluster.

**Expected behavior**
alembic_version table should get replicated on all shared and all replicas. so that wherever it connects, it just start exectuting migration script till where it has reached alread.

**Versions**

- [clickhouse-server]:23.11.5.29
- Python version: 3.10.12

Attached code to cleanup alembic_version table irrespective of whichever shard it runs. This behavior executes all scripts always to be run. Need a meachanism where alemic_version and values in that table should get replicated across all nodes nodes
![image](https://github.com/xzkostyan/clickhouse-sqlalchemy/assets/109265587/62fd4ce7-3cf6-4468-afb9-cd78b306d2df)

**Comment by xzkostyan** [comment]
See #240.

**Comment by xzkostyan** [comment]
I've added cluster example in https://github.com/xzkostyan/clickhouse-sqlalchemy-alembic-example
