### ISSUE TITLE
Alembic_Version Records disappered after clickhouse alembic migration

### ISSUE THREAD

**Issue by vikrant-mah-dhimate** [xzkostyan/clickhouse-sqlalchemy#311]
**Describe the bug**
Thanks @xzkostyan for providing alembic migration [example](https://github.com/xzkostyan/clickhouse-sqlalchemy-alembic-example) for cluster mode. I tried to use the suggested code, and it really replicated alembic version to all nodes. But when checked after certain time, the expand revision_id was missing from all nodes (when expand was ran first, followed by contract)
![clickhouse-alembic](https://github.com/xzkostyan/clickhouse-sqlalchemy/assets/109265587/5a595d59-37ea-4e29-b821-7ec0045f43ce)

**To Reproduce**
Install clickhouse cluster (e.g. https://github.com/tetafro/clickhouse-cluster) and access it using one of the node endpoint. This randomly connects to any one of the shared-replica from cluster.

**Expected behavior**
alembic_version table should get replicated on all shared and all replicas. It should persist alembic_version information for expand and contract appropriately.

**Versions**
Python version: 3.10.12
Clickhouse: 23.10.2.13

- Code snippet
![code](https://github.com/xzkostyan/clickhouse-sqlalchemy/assets/109265587/4cd29e93-126a-4028-a527-09354a2494f8)

**Comment by xzkostyan** [comment]
Hi.

This is how alembic works. In case of postgresql `alembic_version` stores only one row. If you combine this mechanism with `Replacing` engine rows will disappear after merge.

**Comment by vikrant-mah-dhimate** [comment]
@xzkostyan May I know what is the way we can handle both expand and contract migration in cluster mode by persisting both expand and contract revision (how it does for psql)?

**Comment by xzkostyan** [comment]
> same as how it does for psql, as we are using postgresql and it works correctly for postgresql by persisting both version_ids

Can you provide example for PG?

**Comment by vikrant-mah-dhimate** [comment]
@xzkostyan here is the code snippet and postgres snippet attached. 
![image](https://github.com/xzkostyan/clickhouse-sqlalchemy/assets/109265587/8e6460b0-7196-4969-a0f0-d08c85bbe70f)

```
sample=# select * from alembic_version ;
 version_num
--------------
 314abe8f5fce
 9e15486b29e1
(2 rows)

sample=#
sample=#
sample=# \d alembic_version
                    Table "public.alembic_version"
   Column    |         Type          | Collation | Nullable | Default
-------------+-----------------------+-----------+----------+---------
 version_num | character varying(32) |           | not null |
Indexes:
    "alembic_version_pkc" PRIMARY KEY, btree (version_num)

sample=#
```

Additionally, the executions are triggered by providing expand and contract BRANCH in below docker command.
```
docker run --pull=always --rm \
        -v ${PWD}/../${SERVICE}/migrations/contract:/alembic/contract \
        -v ${PWD}/../${SERVICE}/migrations/expand:/alembic/expand \
        --net default \
        -e "POSTGRES_USERNAME=" \
        -e "POSTGRES_PASSWORD=" \
        -e "POSTGRES_HOST=" \
        -e "POSTGRES_PORT=5432" \
        -e "POSTGRES_DB_NAME=" \
        -e "POSTGRES_MANAGED_DB_NAME=${SERVICE}"\
        -e "POSTGRES_MANAGED_PASSWORD="\
        alembic:1.13 \
        upgrade ${BRANCH}@head
        ```

**Comment by vikrant-mah-dhimate** [comment]
@xzkostyan could you please check the above code and suggest for clickhouse? 
cc: @s-dhamodhran @arunmahendran
