### ISSUE TITLE
Support Lightweight DELETE Statement

### ISSUE THREAD

**Issue by franz101** [xzkostyan/clickhouse-sqlalchemy#329]
```
-- Deletes all rows from the `hits` table where the `Title` column contains the text `hello`
DELETE FROM hits WHERE Title LIKE '%hello%';
```

https://clickhouse.com/docs/en/sql-reference/statements/delete

Currently:
```
with clickhouse_client() as db_read:
    data = db_read.query(
        Record
    ).where(Record.node_id==data[0].node_id).delete()

``` would fail and ALTER TABLE is not recommended

**Comment by xzkostyan** [comment]
There is lightweight delete support: https://clickhouse-sqlalchemy.readthedocs.io/en/latest/features.html#update-and-delete

I don't know what `clickhouse_client()` returns. Feel free to add more context to the issue.

**Comment by franz101** [comment]
@xzkostyan this is not lightweight though. it returns:
```
ALTER TABLE ... DELETE WHERE x = 25
```

syntax should be:
```
-- Deletes all rows from the `hits` table where the `Title` column contains the text `hello`
DELETE FROM hits WHERE Title LIKE '%hello%';
```
https://clickhouse.com/docs/en/sql-reference/statements/delete
