### ISSUE TITLE
ARRAY JOIN

### ISSUE THREAD

**Issue by cogtepsum** [xzkostyan/clickhouse-sqlalchemy#34]
Is there a way to add `ARRAY JOIN` clause to my query?

**Comment by xzkostyan** [comment]
Hi.

Currently `ARRAY JOIN` is not supported.

**Comment by nitoqq** [comment]
https://github.com/xzkostyan/clickhouse-sqlalchemy/blob/3609d30f48af7be867a55c87ac24bf50bc1a5b18/clickhouse_sqlalchemy/sql/selectable.py#L23

This ticket should be closed I think

**Comment by cogtepsum** [comment]
Looks like it, thanks!
