### ISSUE TITLE
Error in get_columns with ClickHouse >=18.15

### ISSUE THREAD

**Issue by VerusK** [xzkostyan/clickhouse-sqlalchemy#43]
Getting error when calling function `clickhouse_sqlalchemy.drivers.base.ClickHouseDialect#get_columns`:
```
packages/clickhouse_sqlalchemy/drivers/base.py", line 424, in get_columns
    for name, type_, default_type, default_expression in rows:
ValueError: too many values to unpack (expected 4)
```

this happens in new version of Clickhouse because the added new column `comment_expression` - https://github.com/yandex/ClickHouse/blame/7beb25eaaf6a31399c8ad9355fd93789ea068b6f/dbms/src/Interpreters/InterpreterDescribeQuery.cpp#L48

**Comment by xzkostyan** [comment]
Fixed in latest master: https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/f3e30ea4e75d74b39862bdef762e33be1e0b6476. This fix will be in upcoming release.

**Comment by VerusK** [comment]
@xzkostyan is it possible to make backport of this changes to 0.0.5? :)
It's almost impossible for us to update SQLAlchemy to newer version :(

**Comment by xzkostyan** [comment]
@VerusK unfortunately python packages are immutable. It's not possible to alter version with newer code.

What SA version do you use?

**Comment by VerusK** [comment]
@xzkostyan we are using 1.0.19

**Comment by xzkostyan** [comment]
It's highly recommended to use current SA "Maintenance" series.
We faced with this problem and there was hotfix for older SA-version. You can use [this branch](https://github.com/xzkostyan/clickhouse-sqlalchemy/tree/old-sa-describe-table-fix) as temporary solution.
