### ISSUE TITLE
Wrong Enum usage

### ISSUE THREAD

**Issue by VerusK** [xzkostyan/clickhouse-sqlalchemy#57]
`clickhouse_sqlalchemy/drivers/base.py:583` looks like this code is never called. 
Code: `type_enum = enum.Enum('%s_enum' % name, options)` 
`Enum` accepts only one arg.

**Comment by xzkostyan** [comment]
It seems that constructor can accept two arguments: https://docs.python.org/3/library/enum.html#functional-api
