### ISSUE TITLE
AttributeError: 'Select' object has no attribute '_array_join'

### ISSUE THREAD

**Issue by ShiawasenaHoshi** [xzkostyan/clickhouse-sqlalchemy#60]
When I updated clickhouse-sqlalchemy from repo I got exception on select-query `OrmObject.query.filter_by(id=1]).first()`:

```
  File "/home/vasily/PycharmProjects/np_diff/venv/lib/python3.6/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 232, in _compose_select_body
    if select._array_join is not None:
AttributeError: 'Select' object has no attribute '_array_join'
```

If I just comment this two lines in /driver/base.py
 ```
  if select._array_join is not None:
            text += select._array_join._compiler_dispatch(self, **kwargs)
```
or add check
`  if "_array_join" in select.__dict__.keys() and select._array_join is not None:
`
exception disappear. But, I'm sure it's wrong way to fix. Do I have to update sqlalchemy (I use 1.3.4) or something else?

**Comment by xzkostyan** [comment]
It seems that you used pure SQLAlchemy `select`. You should use `select` from `clickhouse_sqlalchemy.sql.selectable`. It includes all required `clickhouse-sqlalchemy` magic.
