### ISSUE TITLE
Do you plan to implement DELETE and UPDATE statements?

### ISSUE THREAD

**Issue by sdrenn** [xzkostyan/clickhouse-sqlalchemy#65]
Sorry, if it's not the right place to ask, I just don't know, where is.

**Comment by xzkostyan** [comment]
Hi.

It totally OK to ask here. Currently I don't have enough time for this project. But I'll try to add basic delete/updates in a couple of months. It's not so difficult.

If you'd like to make PR with this features it will be awesome. :)

**Comment by sdrenn** [comment]
Thanks for fast answer!

Right after I asked, I found, that Clickhouse do not support atomics for update and delete. Wouldn't that be a problem? I mean, somebody would make a try-except with rollback, as he always did for other databases, and one not-so-bright day he'd realise, that it's not working that way.

**Comment by xzkostyan** [comment]
Well it can be a problem with atomicity.

There is no transactions in ClickHouse right now. So can't do rollback. "Transactions" support is product roadmap but I don't know how they will work.

**Comment by xzkostyan** [comment]
This features awaliable in latest master.
