### ISSUE TITLE
 is it possible to create ReplicatedReplacingMergeTree

### ISSUE THREAD

**Issue by serlex777** [xzkostyan/clickhouse-sqlalchemy#70]

**Comment by xzkostyan** [comment]
Hi.

I thing we forget to add this engine previosly. [Fix](https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/6691d12493e79f5ba9c5458dd115e6972c307614) in latest master.

**Comment by xzkostyan** [comment]
@serlex777 should we close this issue?
