### ISSUE TITLE
Получаю данные в обратном порядке

### ISSUE THREAD

**Issue by mii13** [xzkostyan/clickhouse-sqlalchemy#77]
Здравствуйте. 
В http версии протокола получаю данные в обратном порядке. Проблема наблюдается для версии  0.1.0 и выше.

```
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker


engine = create_engine(uri)
Session = sessionmaker()
Session.configure(bind=engine)
session = Session()
print(list(session.execute(text('select x from test_table order by x'))))
```
Результат для версии 0.0.10:
`[(1,), (2,), (3,), (4,)]`
Результат для версии 0.1.2:
`[(4,), (3,), (2,), (1,)]`

Информация о таблице
```
create table test_table
(
  x Int32
)
  engine = Memory;
```
Причиной данной поведении может быть изменения в методе `clickhouse_sqlalchemy.drivers.http.connector.Cursor._process_response`. Ранее ответ от кликхауса реверсился, в новых версиях убрали это.

python3.6
SQLAlchemy==1.3.13

Спасибо.

**Comment by xzkostyan** [comment]
Привет.

Да, это сломалось при рефакторинге. В качестве workaround можно вызывать `.fetchall()`. С ним порядок сохраняется и в новых версиях.

```python
from sqlalchemy import create_engine, text 
from sqlalchemy.orm import sessionmaker 
 
uri = 'clickhouse+http://default:@localhost' 
 
engine = create_engine(uri) 
Session = sessionmaker() 
Session.configure(bind=engine) 
session = Session() 
print(list(session.execute('select * from system.numbers limit 5').fetchall()))
[(0,), (1,), (2,), (3,), (4,)]
```

Почему вы используете http-диалект вместо native-диалект?

**Comment by mii13** [comment]
Открыт порт только на http подключение.
В следующем релизе, можно ли ожидать исправление данного поведение с `fetchone`?
Помимо трафика, у native-диалекта есть еще преимущества над http?

**Comment by xzkostyan** [comment]
Да, в следующем релизе это будет исправлено.

Если таскать большое количество данных между клиентом и сервером, то native лучше с точки зрения производительности (массив int-ов бинарно (де)сериализуется быстрее, чем в текст). Если данных между клиентом и сервером немного путешествует, то разницы в общем-то немного. Руки никак не дойдут сделать их сравнение.

**Comment by mii13** [comment]
Спасибо за развернутый ответ!

**Comment by xzkostyan** [comment]
Пофиксил в [последнем master](https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/08eb01c6b308aa6ba6b7827116a6a93beeeec5cb).

**Comment by mii13** [comment]
прошу прощение за бестактность.
на мой взгляд `row.pop(0)` будет медленнее чем `row = row[::-1]; row.pop()`.

**Comment by xzkostyan** [comment]
Да, конечно, второй вариант будет быстрее. Подумаю над его возвращением.

**Comment by mii13** [comment]
Немного поэкспериментировал `row.pop(0)` будет быстрее для небольших данных (до 40_000):
for 1_000_000
`python -m timeit -r 1 -u msec -s 'l = list(range(1_000_000))' 'while len(l) > 0: l.pop(0)'`
`10 loops, best of 1: 5.24e+04 msec per loop`

`python -m timeit -r 1 -u msec -s 'l = list(range(1_000_000))' 'l = l[::-1]' 'while len(l) > 0: l.pop()'`
`1000000 loops, best of 1: 0.000296 msec per loop`

for 1_000
`python -m timeit -r 1 -u usec -s 'l = list(range(1_000))' 'while len(l) > 0: l.pop(0)'`
`10000000 loops, best of 1: 0.0675 usec per loop`

`python -m timeit -r 1 -u usec -s 'l = list(range(1_000))' 'l = l[::-1]' 'while len(l) > 0: l.pop()'`
`10000000 loops, best of 1: 0.141 usec per loop`
