### ISSUE TITLE
FINAL modifier

### ISSUE THREAD

**Issue by sdrenn** [xzkostyan/clickhouse-sqlalchemy#78]
Is it possible to apply FINAL modifier to query?
[https://clickhouse.tech/docs/ru/query_language/select/#select-from-final](url)

**Comment by xzkostyan** [comment]
Hi.

Currently FINAL modifier is not supported. But it can be added. See `SAMPLE` clause for example: https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/1178e7ee66cd477c983c63baa5ac3efa094f106b

**Comment by sdrenn** [comment]
I tried to run tests as described in your README. They failed, asking for connection to database. Can you tell, how to setup database for testing?

**Comment by xzkostyan** [comment]
You can [install clickhouse-server locally](https://clickhouse.tech/docs/en/single/#installation) (is case of linux or macos).

Or [use docker](https://hub.docker.com/r/yandex/clickhouse-server/) to run it in container:

```bash
docker run -p 9000:9000 -t  --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:19.15.6.21
```

Anyway you can make a PR and [Travis-CI will run tests](https://travis-ci.org/xzkostyan/clickhouse-sqlalchemy/pull_requests) for you.

**Comment by xzkostyan** [comment]
Done in https://github.com/xzkostyan/clickhouse-sqlalchemy/pull/79.
