### ISSUE TITLE
INSERT is broken

### ISSUE THREAD

**Issue by sdrenn** [xzkostyan/clickhouse-sqlalchemy#83]
I found this code
```        
pos = rv.rfind('VALUES (')
# Remove (%s)-templates from VALUES clause if exists.
# ClickHouse server since version 19.3.3 parse query after VALUES and
# allows inplace parameters.
# Example: INSERT INTO test (x) VALUES (1), (2).
if pos != -1:
    rv = rv[:pos + 6]
```
in base.py in function `visit_insert`

It truncates `rv` from `INSERT INTO data (param) VALUES (%(param)s)` to `INSERT INTO data (param) VALUES`

And I didn't found a test, that should check that.

**Comment by xzkostyan** [comment]
It should be done only for native dialect. This was fixed in https://github.com/xzkostyan/clickhouse-sqlalchemy/pull/73.
