### ISSUE TITLE
Strage behaviour with Clickhouse 20.1 using Superset

### ISSUE THREAD

**Issue by durchgedreht** [xzkostyan/clickhouse-sqlalchemy#84]
Ok, so here comes a nice one: We are using API mode, not native with Clickhouse 20.1.4.1, clickhouse-sqlalchemy was installed today with PIP, so should be latest official version available there. 

When querying the DB its seems, there's data missing and corrupt column headers:

The first 2 rows are broken and will not be interpreted as real data, so results with less than 2 rows will show no data. This is not dependent on the result, table or data, so an overall behaviour. As Crosscheck I used JDBC/DBeaver and results are looking fine there. 

Following table has 7 entries with IDs from 1 to 7:

<img width="570" alt="Screenshot 2020-02-18 at 17 46 54" src="https://user-images.githubusercontent.com/4490840/74763259-cc4acd80-527f-11ea-9fea-6af38afa74f1.png">

The Count shows even no data at all:

<img width="486" alt="Screenshot 2020-02-18 at 17 47 10" src="https://user-images.githubusercontent.com/4490840/74763266-cf45be00-527f-11ea-941d-8c368a17a72e.png">

Verification with DBeaver and JDBC driver looks good:

<img width="153" alt="Screenshot 2020-02-18 at 17 47 34" src="https://user-images.githubusercontent.com/4490840/74763276-d1a81800-527f-11ea-8f83-917e257de7ce.png">

Also sometimes the column header is broken and seems to "merge" come columns. Note the "1_1", "0_1", "0_2" and "1_2" are int values from the first two columns from the resultset concatenated with an underscore! 

<img width="1298" alt="Screenshot 2020-02-18 at 17 39 47" src="https://user-images.githubusercontent.com/4490840/74763527-467b5200-5280-11ea-9b4b-6b82b8f53e90.png">
 
Some of this seems to be related to varchars (as these are also shown as NullType in the Column overview, so some Metadata seems broken or at least affected). Hash is a varchar:

<img width="311" alt="Screenshot 2020-02-18 at 17 40 20" src="https://user-images.githubusercontent.com/4490840/74771351-4a15d580-528e-11ea-9620-6cb3f2e8f87f.png">

**Comment by xzkostyan** [comment]
The same issue: https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/14

There is a `FORMAT` trick for HTTP transport that requires custom session.

**Comment by durchgedreht** [comment]
Thanks for the quick response - that's spot on! One follow up question: As we do not have access to the code directly as we're using sqlalchemy underneath Superset - is there a way to change behaviour based on connection parameters - enforcing "FORMAT TabSeparatedWithNamesAndTypes" ? Or are we doomed in this case?

Also it would be great to add some more details to the readme (which I was indeed reading), but it's not very obvious there's different behaviour by engine call vs session call (nor is it intuitive). When starting with a green field project, you'll directly hit this, so no problem, but if it's covered behind a tool it's a really no big fun debugging.

**Comment by xzkostyan** [comment]
Sorry for late response. You can specify different DSN: `clickhouse+ native://` as database endpoint. Native protocol does not require explicit `FORMAT` clause rendering.
