### ISSUE TITLE
Support `CODEC` column expressions

### ISSUE THREAD

**Issue by athre0z** [xzkostyan/clickhouse-sqlalchemy#88]
Currently, it doesn't appear to be possible to specify [column compression codecs](https://clickhouse.tech/docs/en/query_language/create/#codecs) when using declarative tables. For many columns, monotonously growing `DateTime` columns in particular, usage of such expressions can result in extreme compression rate and performance improvements.

Would you in general like to support these? I'd be willing to contribute the required changes, however my experience with SQLAlchemy is rather limited, so I'd need some guidance on how that would have to be designed. It appears like it is possible to handle extra arguments passed to the `Column` constructor and adding an argument such as `codec=['DoubleDelta', 'ZSTD']` looks like to way to go for me personally, but I might be horribly wrong.

**Comment by xzkostyan** [comment]
Sure, it'll be good to have this feature support.

Here are some highlights on this feature implementation:
* You can [specify](https://github.com/zzzeek/sqlalchemy/blob/rel_1_3_13/lib/sqlalchemy/sql/schema.py#L1395) dialect-dependent options in `Column` constructor. Like `Column(..., clickhouse_codec='XXX')`. `clickhouse_` prefix is required.
* Column rendering is [taking place at compiler.visit_column](https://github.com/zzzeek/sqlalchemy/blob/rel_1_3_13/lib/sqlalchemy/sql/compiler.py#L862).
* You should modify already customezed `visit_column` by using `column.dialect_options['clickhouse']['codec']`. Customized compiler is placed here: `clickhouse_sqlalchemy.drivers.base.ClickHouseCompiler.visit_column`.

Feel free to ask further questions.
