### ISSUE TITLE
sqlalchemy.Boolean renders with a syntax error

### ISSUE THREAD

**Issue by vmarkovtsev** [xzkostyan/clickhouse-sqlalchemy#93]
```python
sqlalchemy.Table(
    "test",
    metadata,
    sqlalchemy.Column("id", sqlalchemy.Integer, primary_key=True),
    sqlalchemy.Column("completed", sqlalchemy.Boolean),
    clickhouse_sqlalchemy.engines.Memory(),
)
```
renders to
```
CREATE TABLE notes (
	id INTEGER,
	completed BOOLEAN, 
	, 
	CHECK (completed IN (0, 1))
) ENGINE = Memory
```
in `metadata.create_all(engine)`.
which raises a syntax error server-side.

**Comment by xzkostyan** [comment]
In ClickHouse SQL dialect there is no boolean type? To which ClickHouse type `sqlalchemy.Boolean` should be rendered?

**Comment by vmarkovtsev** [comment]
There are two separate issues here, a critical one and a "nice to have" one.

The critical is: there should be some validation of the supported types on the client so that we don't send invalid SQL (or whatever ClickHouse calls it) to the server.

The "nice to have" is: redirecting `visit_BOOLEAN` to `visit_WHATEVER_INTEGER_TYPE_CLICKHOUSE_SUPPORTS`. That's how I hacked it locally. I personally don't care whether it is int8 or int32, but I know that using boolean columns is quite common, and adapting the code from (say) Postgres to CH would become smoother. This feature could be optional and disabled by default so that the purists are happy.

**Comment by xzkostyan** [comment]
Fixed [in master](https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/41a23da6f13c5554cb88e5c85cffb868ffa77117).

**Comment by vmarkovtsev** [comment]
Thanks a lot!
