### ISSUE TITLE
MATERIALIZED, ALIAS columns

### ISSUE THREAD

**Issue by bryzgaloff** [xzkostyan/clickhouse-sqlalchemy#96]
How can one create a [MATERIALIZED or ALIAS](https://clickhouse.tech/docs/en/sql-reference/statements/create/#create-default-values) column?

I would like to create such a table:
```sql
CREATE TABLE events (
    eventDatetime DateTime('UTC') MATERIALIZED now(),
    eventDate Date MATERIALIZED toDate(eventDatetime, 'UTC'),
    eventName LowCardinality(String),
    …
```

I have tried different options:
* [Computed](https://docs.sqlalchemy.org/en/13/core/defaults.html#computed-generated-always-as-columns) results into `GENERATED ALWAYS AS` which is not a correct syntax for CH.
* [ColumnDefault](https://docs.sqlalchemy.org/en/13/core/defaults.html#sqlalchemy.schema.ColumnDefault) generates empty output for default value with or without `text` (`ColumnDefault(text('MATERIALIZED now()'))`).
* [DefaultClause](https://docs.sqlalchemy.org/en/13/core/defaults.html#sqlalchemy.schema.DefaultClause) produces `DEFAULT MATERIALIZED now()` which is not a correct syntax.
* [FetchedValue](https://docs.sqlalchemy.org/en/13/core/defaults.html#sqlalchemy.schema.FetchedValue) without `text` generates empty output and with `text` results into `TypeError: Boolean value of this clause is not defined`.

I am quite new to SQLAlchemy and possibly missing something significant. Please tell me how to create a materialized/alias field. Thank you in advance!

**Comment by xzkostyan** [comment]
Hi.

I've added `MATERIALIZED` and `ALIAS` defaults in latest master: https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/e92bbf2d924b3fc928627f9df799ba85c1447574.

You can see usage examples [in tests](https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/e92bbf2d924b3fc928627f9df799ba85c1447574#diff-b355f89785d2a717f940655695407ee1R171).

**Comment by bryzgaloff** [comment]
Works fine for me, thanks!

Could you please help with a little related question? When I try to define the table as follows:
```python
class Event(Base):
    eventDatetime = Column(
        DateTime, primary_key=True,
        clickhouse_materialized=func.toDateTime(func.now(), 'UTC'),
    )
    eventDate = Column(Date, clickhouse_materialized=eventDatetime)
```

By running this:
```python
uri = 'clickhouse://default:@localhost/test'
engine = create_engine(uri)
print(CreateTable(Event.__table__).compile(engine))
```

I get the following output:
```sql
CREATE TABLE events.raw_events (
	"eventDatetime" DateTime MATERIALIZED toDateTime(now(), 'UTC'), 
	"eventDate" Date MATERIALIZED events.raw_events."eventDatetime",  -- bad output
```

And `events.raw_events."eventDatetime"` is not a correct syntax for ClickHouse. Trying to execute the query I get an error:
```
Missing columns: 'events.raw_events.eventDatetime' while processing query: 'CAST(toDateTime(now(), 'UTC') AS eventDatetime_tmp, 'DateTime') AS eventDatetime, eventDatetime_tmp, CAST(events.raw_events.eventDatetime AS eventDate_tmp, 'Date') AS eventDate, eventDate_tmp', required columns: 'events.raw_events.eventDatetime', source columns: 'eventDatetime': default expression and column type are incompatible.
```

Is there any way to generate field name without database and table names? I mean generating `eventDatetime` instead of `events.raw_events."eventDatetime"`. Thank you in advance.

**Comment by xzkostyan** [comment]
If we pass column instance to `clickhouse_materialized` DDL compiler will render fqdn name for it. This is wrong behavior and should be prevented. [Fix](https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/85d3432bd22e813ea970691f0685445dd5576742) is published in master.

**Comment by xzkostyan** [comment]
Sure: https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/0ff0beedf84d04e43b37fe50de9c12ad7a9b1b6a

**Comment by bryzgaloff** [comment]
Thank you for an amazing operativeness, this completely solves the issue! Waiting for a new release, currently using `master`.
